# 하나씩 차근차근 해보아요

## Setting

In [12]:
import time
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import clear_output
%matplotlib ipympl

In [13]:
'''
site energy -> activation energy -> diffusion rate

site energy(E_i) = -N*(E_b)/2

activation energy(E_a) = E_0 + alpha * E_r
E_r = E_i(end) - E_i(start)

diffusion rate = f*exp(-E_a/(k*T)) (Arrhenius)
f is ~ 10^13 for most metals
'''

def get_site_energy(bond_energy, bond_num):
    return -bond_num * bond_energy/2

def get_activation_energy(e_start, e_end, alpha = 0.1, e0 = 0):
    e_reaction = e_end-e_start
    if e_reaction>=0:
        return e0 + (1+alpha)*e_reaction
    else:
        return e0 + alpha*e_reaction

def get_diffusion_rate(e_a, T=300, f=1E13):
    k_B = 8.617333262145e-5  # Boltzmann constant in eV/K
    return f*np.exp(-e_a/(k_B*T))

In [54]:
# Parameters
# Size of the lattice (height x width)
width = 100  
height = 10

# parameter for diffusion rate
'''
bond energy : 200kJ/mol ~~ 2.07 eV/particle
'''
bond_energy = 2.07 
temperature = 300
e0 = 0.1

# site energy, e_(bond number)
e_site = np.zeros(4)
for i in range(4):
    e_site[i] = get_site_energy(bond_energy, i)
# e_0 = get_site_energy(bond_energy, 0)   
# e_1 = get_site_energy(bond_energy, 1)
# e_2 = get_site_energy(bond_energy, 2)
# e_3 = get_site_energy(bond_energy, 3)

# activation energy, e_a_(start to end)
e_a = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        e_a[i, j] = get_activation_energy(e_site[i], e_site[j], e0=e0)
# e_a_3to0 = get_activation_energy(e_3, e_0, e0=e0)
# e_a_0to3 = get_activation_energy(e_0, e_3, e0=e0)
# e_a_2to3 = get_activation_energy(e_2, e_3, e0=e0)
# e_a_3to2 = get_activation_energy(e_3, e_2, e0=e0)
# e_a_NtoN = get_activation_energy(e_3, e_3, e0=e0)
# e_a_0to1 = get_activation_energy(e_0, e_1, e0=e0)W


# diffusion rate, rate_(start to end)
diffusion_rate = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        diffusion_rate[i, j] = get_diffusion_rate(e_a[i, j], temperature)
# rate_3to0 = get_diffusion_rate(e_a_3to0, temperature)     
# rate_0to3 = get_diffusion_rate(e_a_0to3, temperature)              
# rate_2to3 = get_diffusion_rate(e_a_2to3, temperature)            
# rate_3to2 = get_diffusion_rate(e_a_3to2, temperature)        
# rate_NtoN = get_diffusion_rate(e_a_NtoN, temperature)     
# rate_0to1 = get_diffusion_rate(e_a_0to1, temperature)        

steps = 100
time_elapsed = 0

In [56]:
# value check
print(e_site)
print('-----------------')
print(e_a)
print('-----------------')
print(diffusion_rate)


[  0.  -5. -10. -15.]
-----------------
[[ 0.1 -0.4 -0.9 -1.4]
 [ 5.6  0.1 -0.4 -0.9]
 [11.1  5.6  0.1 -0.4]
 [16.6 11.1  5.6  0.1]]
-----------------
[[2.08965186e+011 5.24450190e+019 1.31623840e+028 3.30342815e+036]
 [8.39731685e-082 2.08965186e+011 5.24450190e+019 1.31623840e+028]
 [3.37448221e-174 8.39731685e-082 2.08965186e+011 5.24450190e+019]
 [1.35604389e-266 3.37448221e-174 8.39731685e-082 2.08965186e+011]]


In [17]:
# function to initialize the lattice
'''
Initialize the lattice
1 : atom
0 : vacancy or vacumm
2 more layer to make vacuum
'''
def init_lattice(width, height):
    lattice = np.ones((height+2, width), dtype=int)
    lattice[0, :] = 0
    lattice[-1, :] = 0

    return lattice

In [58]:
# Function to plot the lattice of circles
def plot_lattice(ax, width, height, atom_radius, lattice):
    for x in range(width):
        for y in range(height+2):
            if lattice[y, x] == 1:
                circle = plt.Circle((x + 0.5, y + 0.5), atom_radius, color='blue')
                ax.add_artist(circle)
    ax.set_xlim(0, width)
    ax.set_ylim(0, height+2)
    ax.set_aspect('equal')
    ax.axis('off')
    plt.tight_layout(pad=0.5)

In [59]:
# Function to draw lattice on prompt
def draw_lattice(lattice):
    height, width = lattice.shape
    for y in range(height):
        for x in range(width):
            if lattice[y, x] == 1:
                print('●', end = '')
            else:
                print(' ', end='')
        print('\n')

In [60]:
'''
function that finds every possible way
1. atom jumped from surface
2. return to previous position(jumped from surface)
3. atom jumped from side(at surface)
4. atom jumped from inside
'''
def get_atoms_around_site(lattice, x, y, total=False):
    height, width = lattice.shape
    # calculate bond number
    if y == height-1:
        down = 0
    else:
        down = lattice[y+1, x]
    if y == 0:
        up = 0
    else:
        up = lattice[y-1, x]
    # PBC at left and right
    right = lattice[y, (x+1)%width]
    left = lattice[y, (x-1)%width]
    
    if total:
        return left+up+right+down
    else:
        return left, up, right, down

def find_candidate(lattice):
    global e_a
    global diffusion_rate
    height, width = lattice.shape
    candidate_table = []
    diffusion_table = []
    motion_table = []
    for x in range(width):
        for y in range(height):
            # find atom(value 1)
            if lattice[y, x] == 1:
                left, up, right, down = get_atoms_around_site(lattice, x, y)
                bond_num = down + up + right + left
                # print(bond_num)
                # classify the atoms by bond_num
                # 0 bond num : jumped atom from surface
                if bond_num == 0:
                    candidate_table.append((y, x))
                    diffusion_table.append(diffusion_rate[0, 3])
                    if y == height-1 :
                        motion_table.append(2)
                    else :
                        motion_table.append(4)
                # 2 bond num : surface atom next to vacancy
                elif bond_num == 2:
                    # print('find')
                    candidate_table.append((y, x))
                    diffusion_table.append(diffusion_rate[2, 3])
                    if left == 0 :
                        motion_table.append(1)
                    else:
                        motion_table.append(3)
                # 3 bond num
                # 3-1. surface atom
                elif bond_num == 3:
                    candidate_table.append((y, x))
                    if left == 0 :
                        num_next_site_bond = get_atoms_around_site(lattice, (x-1+width)%width, y, total=True)
                        motion_table.append(1)
                    elif up == 0 :
                        num_next_site_bond = get_atoms_around_site(lattice, x, y-1, total=True)
                        motion_table.append(2)
                    elif right == 0 :
                        num_next_site_bond = get_atoms_around_site(lattice, (x+1+width)%width, y, total=True)
                        motion_table.append(3)
                    else:
                        num_next_site_bond = get_atoms_around_site(lattice, x, y+1, total=True)
                        motion_table.append(4)
                    
                    if num_next_site_bond == 0:
                        diffusion_table.append(diffusion_rate[3, 0])
                    elif num_next_site_bond == 2:
                        diffusion_table.append(diffusion_rate[3, 2])
                    else:
                        diffusion_table.append(diffusion_rate[3, 3])
                
    
    return candidate_table, diffusion_table, motion_table

In [61]:
# KMC function
def diffuse_one_step(lattice, print_out=False):
    global time_elapsed
    cand, dif, motion = find_candidate(lattice)
    dif = np.array(dif)

    total_dif = np.sum(dif)
    
    # pick 1
    u = np.random.uniform(low=1e-6, high=1)
    u_time = np.random.uniform(low=1e-6, high=1)
    cum_dif = np.cumsum(dif)

    chosen_idx = np.argwhere(u*total_dif < cum_dif)[0][0]

    # print information
    if print_out:
        print(f'total_diff : {total_dif}')
        print(f'chosen : {cand[chosen_idx]} atom')   
    # print(f'motion : {motion[chosen_idx]}')
    # print(cand[chosen_idx])
    # print(motion[chosen_idx])

    # change the lattice
    x, y = cand[chosen_idx][0], cand[chosen_idx][1]

    # get motion
    if motion[chosen_idx] == 1:
        lattice[x, y] = 0
        lattice[x, (y-1+width)%width] = 1
        # if print_out:
        print(f'go left')   
    if motion[chosen_idx] == 2:
        lattice[x, y] = 0
        lattice[x-1 , y] = 1
        if print_out:
            print(f'go up')   
    if motion[chosen_idx] == 3:
        lattice[x, y] = 0
        lattice[x, (y+1)%width] = 1
        # if print_out:
        print(f'go right')   
    if motion[chosen_idx] == 4:
        lattice[x, y] = 0
        lattice[x+1 , y] = 1
        if print_out:
            print(f'go down')   
    
    # time update
    delta_t = -np.log(u_time)/total_dif
    time_elapsed += delta_t

## Animation using text(fast)
---

In [63]:
# Parameters
# Size of the lattice (height x width)
width = 100  
height = 10

# parameter for diffusion rate
'''
bond energy : 200kJ/mol ~~ 2.07 eV/particle
'''
bond_energy = 2.07 
temperature = 300
e0 = 0.1

# site energy, e_(bond number)
e_site = np.zeros(4)
for i in range(4):
    e_site[i] = get_site_energy(bond_energy, i)

# activation energy, e_a_(start to end)
e_a = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        e_a[i, j] = get_activation_energy(e_site[i], e_site[j], e0=e0)

# diffusion rate, rate_(start to end)
diffusion_rate = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        diffusion_rate[i, j] = get_diffusion_rate(e_a[i, j], temperature)
  
steps = 100
time_elapsed = 0

In [64]:
'''
text-based simulation
'''
lattice = init_lattice(width, height)
for i in range(1, steps+1):
    print(f'---------------- step {i} ---------------------')
    diffuse_one_step(lattice, True)
    draw_lattice(lattice)
    print(f'Time elapsed : {time_elapsed}')
    time.sleep(0.01)
    
    # os.system('clear')
    clear_output(wait=True)
    # fig, ax = plt.subplots(figsize=(10, 2))
    # plot_lattice(ax, width, height, atom_radius, lattice)


---------------- step 100 ---------------------
total_diff : 3.443940553482124e+16
chosen : (0, 60) atom
go down
                                                                                                    

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

In [65]:
'''
simulation without visualization
'''
def draw_lattice(lattice):
    height, width = lattice.shape
    for y in range(height):
        for x in range(width):
            if lattice[y, x] == 1:
                print('●', end = '')
            else:
                print(' ', end='')
        print('\n')

steps = 3000
lattice = init_lattice(width, height)
atom_num = lattice.sum()
for i in range(1, steps+1):
    diffuse_one_step(lattice)
    if i % 1000 == 0:
        print(f'---------------- step {i} ---------------------')
        print(f'Time elapsed : {time_elapsed}')
        if lattice.sum() != atom_num:
            print('error!')
            break


---------------- step 1000 ---------------------
Time elapsed : 1.2729314407820725e-11
go right
go right
go left
go right
go right
go right
go left
go left
go left
go right
go left
go right
go right
---------------- step 2000 ---------------------
Time elapsed : 2.5009383027133335e-11
go left
go left
go right
go left
go right
go left
go right
go right
go right
go right
go left
go left
go left
go left
go right
go right
go left
go right
go left
go right
go right
go left
go right
go right
go left
go left
go right
go right
go right
go right
go right
go left
go right
go left
go right
go left
go right
go left
go right
go right
go right
go left
go right
go right
go left
go right
go right
go right
go left
go left
go right
go left
go left
go right
go right
go left
go left
go right
go right
go left
go right
go right
go right
go right
go left
go left
go right
go left
go right
go right
go right
go right
go left
go right
go left
go left
go left
go right
go right
go left
go left
go left
go right
go 

In [66]:
print(lattice.sum())
draw_lattice(lattice)

990
                                              ●                                                     

●●●●●●●●●●●●●●● ● ● ● ●● ● ● ● ●●●●●●●● ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●● ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●● ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●

●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●